### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by cramhead** [yracnet/vscode-nearley-plugin#2]
This is a really cool plugin! Thanks for making it. 
I've been able to use it with standard nodejs approaches, i.e. commonjs with JavaScript.

It would be totally awesome if it could work in my current project that is using the TypeScript preprocessor. 
When I point the tester to the dist file that is generated, i.e. the js file, I get the following error
![image](https://user-images.githubusercontent.com/386035/125675350-b739214e-8955-4641-88c4-fa73813bb32e.png)

The rules seem to be there but are exported differently
![image](https://user-images.githubusercontent.com/386035/125675726-c1d849ef-7fe8-4e0f-ad5b-9dcc3b042536.png)
then in the working JavaScript configuration
![image](https://user-images.githubusercontent.com/386035/125675892-bcdaf899-6126-4bdc-83e4-d7d75c5ab69e.png)

**Comment by yracnet** [comment]
Hi, 
Thank you for use my plugin in your project.

 But I think that this error or requirement should be send to `nearley team,` because I use the `nearleyc` for compile the file. (https://github.com/kach/nearley)

Sorry for the late response

**Comment by cramhead** [comment]
Ok. I'm no longer using nearley.js. Closing
